name: CodeRabbit Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  coderabbit-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: CodeRabbit Review
        uses: coderabbitai/coderabbit-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          debug: false
          max_files: 50
          
      - name: Extract CodeRabbit Suggestions
        id: extract
        run: |
          echo "suggestions_file=coderabbit-suggestions.md" >> $GITHUB_OUTPUT
          
      - name: Upload CodeRabbit Analysis
        uses: actions/upload-artifact@v4
        with:
          name: coderabbit-analysis-${{ github.event.number }}
          path: |
            coderabbit-suggestions.md
            
  claude-code-integration:
    needs: coderabbit-review
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download CodeRabbit Analysis
        uses: actions/download-artifact@v4
        with:
          name: coderabbit-analysis-${{ github.event.number }}
          
      - name: Format for Claude Code
        run: |
          echo "🤖 CODERABBIT SYNC" > claude-instructions.md
          echo "" >> claude-instructions.md
          echo "CodeRabbit encontrou estas issues:" >> claude-instructions.md
          echo "" >> claude-instructions.md
          
          if [ -f coderabbit-suggestions.md ]; then
            cat coderabbit-suggestions.md >> claude-instructions.md
          else
            echo "Nenhuma sugestão encontrada" >> claude-instructions.md
          fi
          
          echo "" >> claude-instructions.md
          echo "Por favor:" >> claude-instructions.md
          echo "1. Analise cada sugestão" >> claude-instructions.md
          echo "2. Aplique as correções necessárias" >> claude-instructions.md
          echo "3. Explique o que foi feito" >> claude-instructions.md
          echo "4. Mostre antes/depois do código" >> claude-instructions.md
          
      - name: Comment on PR with Claude Instructions
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            let body = "## 🤖 CodeRabbit Analysis Ready for Claude Code\n\n";
            
            if (fs.existsSync('claude-instructions.md')) {
              const instructions = fs.readFileSync('claude-instructions.md', 'utf8');
              body += "```\n" + instructions + "\n```";
            } else {
              body += "Nenhuma sugestão do CodeRabbit encontrada.";
            }
            
            body += "\n\n---\n";
            body += "*Copy the content above and paste it to Claude Code for automatic fixes*";
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
